---
title: "415 Project"
date: "2019/04/04"
output: pdf_document
---
reviews_ed2 is the most important data frame, keep it!

## Data Import & Cleaning

```{r data import}
library(tidyverse)
library(stringr)
reviews<- read_csv("Hotel_Reviews.csv", col_types = cols(Hotel_Address=col_character(), Additional_Number_of_Scoring=col_integer(), Review_Date=col_character(), Average_Score=col_double(), Hotel_Name=col_character(), Reviewer_Nationality=col_character(), Negative_Review=col_character(), Review_Total_Negative_Word_Counts=col_integer(), Total_Number_of_Reviews=col_integer(), Positive_Review=col_character(), Review_Total_Positive_Word_Counts=col_integer(), Total_Number_of_Reviews_Reviewer_Has_Given=col_integer(), Reviewer_Score=col_double(), Tags=col_character(), days_since_review=col_character(), lat=col_double(), lng=col_double()))
problems(reviews)
(reviews)
```

```{r transforming variables}
reviews_ed1<- reviews%>% mutate(days_since_review=str_extract(days_since_review, "^\\d+"))%>% mutate(days_since_review=as.numeric(days_since_review))
```

```{r finding out top20 sources of tourist}
## temp_1<- reviews%>% group_by(Reviewer_Nationality)%>% summarize(num_tourist_by_nation=n())%>% arrange(desc(num_tourist_by_nation))%>% head(n=20) ##

## top20_country<- temp_1$Reviewer_Nationality ##
```

```{r some basic data visualization}
reviews_ed1%>% filter(str_detect(Reviewer_Nationality, top20_country))%>% group_by(Reviewer_Nationality)%>% summarize(Top_AvSC=mean(Reviewer_Score))%>% arrange(desc(Top_AvSC))

reviews_ed1%>% filter(str_detect(Reviewer_Nationality, top20_country)) %>% group_by(Reviewer_Nationality)%>% summarize(AvSc=mean(Average_Score))%>% arrange(desc(AvSc))%>% head(n=20)  

reviews_ed1%>% filter(str_detect(Reviewer_Nationality, top5_country))%>% group_by(Reviewer_Nationality)%>% ggplot(aes(x=reorder(factor(Reviewer_Nationality), Reviewer_Score, FUN=median), y=Reviewer_Score))+ geom_boxplot()

reviews_ed2<- reviews_ed1%>% mutate(Hotel_Country=word(reviews_ed1$Hotel_Address,-1))
reviews_ed2<- reviews_ed2%>% mutate(Hotel_Country=str_replace(reviews_ed2$Hotel_Country,"Kingdom","UK"))
```

```{r text minning sample}
NEGATIVE<- reviews_ed2%>% filter(!str_detect(Negative_Review, "No Negative"))%>% select(Negative_Review)

temp_NE_10<- str_replace_all(NEGATIVE$Negative_Review,pattern = "[[:punct:]]", "")%>% head(n=10)#remove extra whitespaces#
NE_10_list<- str_split(temp_NE_10,boundary("word"))
NE_10_All_Words<- unlist(NE_10_list)
unique_words_NE_10 <- unique(NE_10_All_Words)#finding unique words in the splitted and unlistted negative review (10)
z<-vector("integer", length(unique(NE_10_All_Words)))
for(i in seq_along(z)){
  z[i]=sum(NE_10_All_Words==unique_words_NE_10[i])
}#use vector z to store the occurences of each unique words in negative revie
top_30_order <- order(z, decreasing = TRUE)[1:30]
(top_30_words <- unique_words_NE_10[top_30_order])
```

```{r factorizing countries in regions}
## reviews_ed3<-reviews_ed2%>%filter(str_detect(Reviewer_Nationality, top20_country)) ##
```

```{r univariate regression}
data_for_lm1<- reviews_ed2%>% group_by(Hotel_Name)%>% summarize(negative_ratio=mean(Negative_Review!="No Negative"),score=mean(Average_Score))%>% filter(!is.na(negative_ratio))

lm1<- lm(score~negative_ratio,data=data_for_lm1)
beta1<- coef(lm1)
data_for_lm1%>% ggplot(aes(x=negative_ratio,y=score))+geom_point()+geom_abline(intercept=beta1[1],slope=beta1[2],color="red")

data_for_lm1%>% add_residuals(lm1)%>% ggplot(aes(resid))+geom_freqpoly(binwidth=1)
data_for_lm1%>% add_residuals(lm1)%>% ggplot(aes(x=negative_ratio,y=resid))+geom_ref_line(h=0)+geom_point()

summary(lm(Reviewer_Score~days_since_review,data=reviews_ed2))

reviews_ed5<- reviews_ed2%>% filter(Negative_Review!="No Negative", Positive_Review!="No Positive")%>% mutate(difference=Review_Total_Negative_Word_Counts-Review_Total_Positive_Word_Counts)
summary(lm(Reviewer_Score~difference,data=reviews_ed5))

reviews_ed6<- reviews_ed5%>% mutate(num_of_reviews=Total_Number_of_Reviews_Reviewer_Has_Given)

summary(lm(Reviewer_Score~num_of_reviews-1,data=reviews_ed6))
```

```{r text minning for negative review}
NEGATIVE_ed2<- reviews_ed2%>% filter(!str_detect(Negative_Review, "No Negative"))%>% select(Negative_Review,Reviewer_Nationality)

temp_4<- NEGATIVE_ed2%>% select(Reviewer_Nationality)

library(tidyverse)
library(lubridate)
library(dplyr)
library(tidytext)
library(tm)
library(SnowballC)
library(modelr)
library(stringr)

neg_for_minning<- Corpus(VectorSource(NEGATIVE_ed2$Negative_Review))
neg_for_minning_ed1<- tm_map(neg_for_minning, removeWords, stopwords('english'))
neg_for_minning_ed2<- neg_for_minning_ed1%>% tm_map(content_transformer(tolower))%>% tm_map(removeNumbers)%>% tm_map(removePunctuation)%>% tm_map(stripWhitespace)%>% tm_map(removeWords, c("i","my","you","our","the","we","they","he","she","am","it","when","in","t"))

temp_3<- data.frame(Negative_Review=sapply(neg_for_minning_ed2,as.character),stringsAsFactors=FALSE)

NEGATIVE_ed3<- bind_cols(temp_4,temp_3)

top_10_country_df<- reviews%>% group_by(Reviewer_Nationality)%>% summarize(num_tourist_by_nation=n())%>% arrange(desc(num_tourist_by_nation))%>% head(n=10)%>% select(Reviewer_Nationality)
top_10_country<- top_10_country_df$Reviewer_Nationality

NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)

NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% unnest_tokens(bigram,Negative_Review,token="ngrams",n=2)%>% count(Reviewer_Nationality,bigram,sort=TRUE)%>% mutate(bigram=factor(bigram,levels=rev(unique(bigram))))%>% group_by(Reviewer_Nationality)%>% top_n(5)%>% arrange(desc(n),.by_group=TRUE) ##two words, and group by country##

neg_bigram<- NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% mutate(Reviewer_Nationality=fct_collapse(Reviewer_Nationality,UK_IR=c("United Kingdom","Ireland"),NE_SW_GE=c("Netherlands","Switzerland","Germany"),Middle_East=c("United Arab Emirates","Saudi Arabia"),US_CA=c("United States of America","Canada"),AUS="Australia"))%>% unnest_tokens(bigram,Negative_Review,token="ngrams",n=2)%>% count(Reviewer_Nationality,bigram,sort=TRUE)

neg_bigram %>%
  arrange(desc(n)) %>%
  mutate(bigram = factor(bigram, levels = rev(unique(bigram)))) %>%
  group_by(Reviewer_Nationality) %>% 
  top_n(5) %>% 
  ungroup() %>%
  ggplot(aes(bigram, n, fill = Reviewer_Nationality)) +
  geom_col(show.legend = FALSE)  +
  facet_wrap(~Reviewer_Nationality, ncol = 2, scales = "free") +
  coord_flip() ##facet wrap group by country##

temp_10<- reviews_ed4%>% select(Negative_Review,Hotel_Country)
neg_bigram_2<- temp_10%>% unnest_tokens(bigram,Negative_Review,token="ngrams",n=2)%>% count(Hotel_Country,bigram,sort=TRUE)
neg_bigram_2 %>%
  arrange(desc(n)) %>%
  mutate(bigram = factor(bigram, levels = rev(unique(bigram)))) %>%
  group_by(Hotel_Country) %>% 
  top_n(5) %>% 
  ungroup() %>%
  ggplot(aes(bigram, n, fill = Hotel_Country)) +
  geom_col(show.legend = FALSE)  +
  facet_wrap(~Hotel_Country, ncol = 2, scales = "free") +
  coord_flip()

t5<- NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% unnest_tokens(bigram,Negative_Review,token="ngrams",n=2)%>% count(bigram,sort=TRUE)%>% top_n(15) ##two words##

t4<- NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% unnest_tokens(word,Negative_Review)%>% count(word,sort=TRUE)%>% top_n(15) ##one word##

t6<- NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% unnest_tokens(triple,Negative_Review,token="ngrams",n=3)%>% count(triple,sort=TRUE)%>% top_n(15) ##three words##

t7<- bind_cols(t4,t5,t6)
t7%>% select(word,bigram,triple)

room_small<- c("room","small","rooms","little")
temp_2<- NEGATIVE_ed3%>% filter(Reviewer_Nationality %in% top_10_country)%>% mutate(small=if_else(str_detect(Negative_Review,room_small),1,0))%>% mutate(breakfast=if_else(str_detect(Negative_Review,"breakfast"),1,0))%>% mutate(bed=if_else(str_detect(Negative_Review,"bed"),1,0))%>% mutate(bathroom=if_else(str_detect(Negative_Review,"bathroom"),1,0))%>% mutate(coffee=if_else(str_detect(Negative_Review,c("tea","coffee","facilities")),1,0))
temp_5<- reviews_ed2%>% filter(!str_detect(Negative_Review, "No Negative"))%>% filter(Reviewer_Nationality %in% top_10_country)%>% select(Reviewer_Score)
NEGATIVE_ed4<- bind_cols(temp_2,temp_5)

reviews_ed3<- reviews_ed2%>% filter(!str_detect(Negative_Review, "No Negative"))%>% filter(Reviewer_Nationality %in% top_10_country)%>% select(days_since_review,Hotel_Country)

reviews_ed4<- bind_cols(NEGATIVE_ed4,reviews_ed3)%>% mutate(Reviewer_Nationality=fct_collapse(Reviewer_Nationality,UK_IR=c("United Kingdom","Ireland"),NE_SW_GE=c("Netherlands","Switzerland","Germany"),Middle_East=c("United Arab Emirates","Saudi Arabia"),US_CA=c("United States of America","Canada"),AUS="Australia"))%>% mutate(Hotel_Country=fct_recode(Hotel_Country,Au="Austria",Fr="France",It="Italy",Ne="Netherlands",Sp="Spain"))

summary(lm(Reviewer_Score~small+breakfast+bed+bathroom+coffee+Reviewer_Nationality+Hotel_Country+days_since_review-1,data=reviews_ed4))

reviews_ed4%>% group_by(Reviewer_Nationality)%>% summarize(AvSC=mean(Reviewer_Score))%>% arrange(desc(AvSC))
```

```{r text minning for positive review}
POSITIVE<- reviews_ed2%>% filter(!str_detect(Positive_Review, "No Positive"))%>% filter(Reviewer_Nationality%in%top_10_country)

pos_for_minning<- Corpus(VectorSource(POSITIVE$Positive_Review))
pos_for_minning_ed1<- pos_for_minning%>% tm_map(content_transformer(tolower))%>% tm_map(removeWords, stopwords('english'))%>% tm_map(removeNumbers)%>% tm_map(removePunctuation)%>% tm_map(stripWhitespace)%>% tm_map(removeWords,c("in","and","the","it","was"))

temp_1<- data.frame(Positive_Review=sapply(pos_for_minning_ed1,as.character),stringsAsFactors=FALSE)

t1<- temp_1%>% unnest_tokens(word,Positive_Review)%>% count(word,sort=TRUE)%>% top_n(15) ##one word##
t2<- temp_1%>% unnest_tokens(bigram,Positive_Review,token="ngrams",n=2)%>% count(bigram,sort=TRUE)%>% top_n(15) ##two word##
t3<- bind_cols(t1,t2)
t3%>% select(word,bigram)

POSITIVE_ed1<- POSITIVE%>% mutate(location=if_else(str_detect(Positive_Review,"location"),1,0))%>% mutate(staff=if_else(str_detect(Positive_Review,"staff"),1,0))%>% mutate(bed=if_else(str_detect(Positive_Review,"bed"),1,0))%>% mutate(clean=if_else(str_detect(Positive_Review,"clean"),1,0))%>% mutate(breakfast=if_else(str_detect(Positive_Review,"breakfast"),1,0))%>% mutate(Reviewer_Nationality=fct_collapse(Reviewer_Nationality,UK_IR=c("United Kingdom","Ireland"),NE_SW_GE=c("Netherlands","Switzerland","Germany"),Middle_East=c("United Arab Emirates","Saudi Arabia"),US_CA=c("United States of America","Canada"),AUS="Australia"))%>% mutate(Hotel_Country=fct_recode(Hotel_Country,Au="Austria",Fr="France",It="Italy",Ne="Netherlands",Sp="Spain"))

temp_6<- POSITIVE%>% select(Reviewer_Nationality)
temp_7<- bind_cols(temp_1,temp_6)%>% mutate(Reviewer_Nationality=fct_collapse(Reviewer_Nationality,UK_IR=c("United Kingdom","Ireland"),NE_SW_GE=c("Netherlands","Switzerland","Germany"),Middle_East=c("United Arab Emirates","Saudi Arabia"),US_CA=c("United States of America","Canada"),AUS="Australia"))
pos_bigram<- temp_7%>% unnest_tokens(bigram,Positive_Review,token="ngrams",n=2)%>% count(Reviewer_Nationality,bigram,sort=TRUE)

temp_8<- POSITIVE%>% select(Hotel_Country)%>% mutate(Hotel_Country=fct_recode(Hotel_Country,Au="Austria",Fr="France",It="Italy",Ne="Netherlands",Sp="Spain"))
temp_9<- bind_cols(temp_1,temp_8)

pos_word<- temp_9%>% unnest_tokens(word,Positive_Review,token="ngrams",n=1)%>% count(Hotel_Country,word,sort=TRUE)

pos_word %>%
  arrange(desc(n)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>%
  group_by(Hotel_Country) %>% 
  top_n(5) %>% 
  ungroup() %>%
  ggplot(aes(word, n, fill = Hotel_Country)) +
  geom_col(show.legend = FALSE)  +
  facet_wrap(~Hotel_Country, ncol = 2, scales = "free") +
  coord_flip()

pos_bigram %>%
  arrange(desc(n)) %>%
  mutate(bigram = factor(bigram, levels = rev(unique(bigram)))) %>%
  group_by(Reviewer_Nationality) %>% 
  top_n(5) %>% 
  ungroup() %>%
  ggplot(aes(bigram, n, fill = Reviewer_Nationality)) +
  geom_col(show.legend = FALSE)  +
  facet_wrap(~Reviewer_Nationality, ncol = 2, scales = "free") +
  coord_flip()

pos_word<- temp_7%>% unnest_tokens(word,Positive_Review,token="ngrams",n=1)%>% count(Reviewer_Nationality,word,sort=TRUE)
pos_word %>%
  arrange(desc(n)) %>%
  mutate(word = factor(word, levels = rev(unique(word)))) %>%
  group_by(Reviewer_Nationality) %>% 
  top_n(5) %>% 
  ungroup() %>%
  ggplot(aes(word, n, fill = Reviewer_Nationality)) +
  geom_col(show.legend = FALSE)  +
  facet_wrap(~Reviewer_Nationality, ncol = 2, scales = "free") +
  coord_flip()

summary(lm(Reviewer_Score~location+staff+bed+clean+breakfast+Reviewer_Nationality+Hotel_Country+days_since_review-1,data=POSITIVE_ed1))
```

```{r}
dummyset <- reviews_ed2 %>%
  mutate(countrydummy = ifelse(Hotel_Country == 'France', 1,
                               ifelse(Hotel_Country == 'Italy', 2,
                                      ifelse(Hotel_Country == 'Netherlands', 3,
                                             ifelse(Hotel_Country == 'Spain', 4,
                                                    ifelse(Hotel_Country == 'UK', 5, 0))))))
         
interaction <- lm(Reviewer_Score ~ Review_Total_Negative_Word_Counts + countrydummy + Review_Total_Negative_Word_Counts:countrydummy, dummyset)

summary(interaction)

beta <- coef(interaction)
beta

library(tidyverse)

ggplot(dummyset) + geom_point(aes(Review_Total_Negative_Word_Counts, Reviewer_Score)) + geom_abline(aes(intercept = beta[1]+beta[3], slope = beta[2]+beta[4]), color = "red", size=1) +
  geom_abline(aes(intercept = beta[1]+2*beta[3], slope = beta[2]+2*beta[4]), color = "green", size=1) +
  geom_abline(aes(intercept = beta[1]+3*beta[3], slope = beta[2]+3*beta[4]), color = "blue", size=1) +
  geom_abline(aes(intercept = beta[1]+4*beta[3], slope = beta[2]+4*beta[4]), color = "yellow", size=1) +
  geom_abline(aes(intercept = beta[1]+5*beta[3], slope = beta[2]+5*beta[4]), color = "orange", size=1) +
  geom_abline(aes(intercept = beta[1]+0*beta[3], slope = beta[2]+0*beta[4]), color = "purple", size=1)
  
```


